enum RuleType {
  individual, // Match specific package name
  nameContains, // App name contains string
  nameStartsWith, // App name starts with string
  regex, // Package name matches regex
  company, // Package name starts with company prefix (e.g., com.facebook)
}

class BlockingRule {
  final int? id;
  final String? name; // Custom rule name, null means auto-generated
  final RuleType type;
  final String pattern; // package name, search string, regex, or company prefix
  final int order; // Lower = higher priority
  final bool enabled;

  // Overlay configuration
  final String? imagePath;
  final String overlayText;
  final double textPositionX; // 0-1
  final double textPositionY; // 0-1
  final double imageScale;
  final double imageOffsetX;
  final double imageOffsetY;

  BlockingRule({
    this.id,
    this.name,
    required this.type,
    required this.pattern,
    required this.order,
    this.enabled = true,
    this.imagePath,
    this.overlayText = 'Stay Focused!',
    this.textPositionX = 0.5,
    this.textPositionY = 0.5,
    this.imageScale = 1.0,
    this.imageOffsetX = 0.0,
    this.imageOffsetY = 0.0,
  });

  BlockingRule copyWith({
    int? id,
    String? name,
    RuleType? type,
    String? pattern,
    int? order,
    bool? enabled,
    String? imagePath,
    String? overlayText,
    double? textPositionX,
    double? textPositionY,
    double? imageScale,
    double? imageOffsetX,
    double? imageOffsetY,
  }) {
    return BlockingRule(
      id: id ?? this.id,
      name: name ?? this.name,
      type: type ?? this.type,
      pattern: pattern ?? this.pattern,
      order: order ?? this.order,
      enabled: enabled ?? this.enabled,
      imagePath: imagePath ?? this.imagePath,
      overlayText: overlayText ?? this.overlayText,
      textPositionX: textPositionX ?? this.textPositionX,
      textPositionY: textPositionY ?? this.textPositionY,
      imageScale: imageScale ?? this.imageScale,
      imageOffsetX: imageOffsetX ?? this.imageOffsetX,
      imageOffsetY: imageOffsetY ?? this.imageOffsetY,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'type': type.index,
      'pattern': pattern,
      'order_index': order,
      'enabled': enabled ? 1 : 0,
      'image_path': imagePath,
      'overlay_text': overlayText,
      'text_position_x': textPositionX,
      'text_position_y': textPositionY,
      'image_scale': imageScale,
      'image_offset_x': imageOffsetX,
      'image_offset_y': imageOffsetY,
    };
  }

  factory BlockingRule.fromMap(Map<String, dynamic> map) {
    return BlockingRule(
      id: map['id'] as int?,
      name: map['name'] as String?,
      type: RuleType.values[map['type'] as int],
      pattern: map['pattern'] as String,
      order: map['order_index'] as int,
      enabled: (map['enabled'] as int) == 1,
      imagePath: map['image_path'] as String?,
      overlayText: map['overlay_text'] as String? ?? 'Stay Focused!',
      textPositionX: (map['text_position_x'] as num?)?.toDouble() ?? 0.5,
      textPositionY: (map['text_position_y'] as num?)?.toDouble() ?? 0.5,
      imageScale: (map['image_scale'] as num?)?.toDouble() ?? 1.0,
      imageOffsetX: (map['image_offset_x'] as num?)?.toDouble() ?? 0.0,
      imageOffsetY: (map['image_offset_y'] as num?)?.toDouble() ?? 0.0,
    );
  }

  String get displayName {
    if (name != null && name!.isNotEmpty) {
      return name!;
    }
    return _autoGeneratedName;
  }

  String get _autoGeneratedName {
    switch (type) {
      case RuleType.individual:
        return pattern.split('.').last; // Show last part of package name
      case RuleType.nameContains:
        return 'Name contains "$pattern"';
      case RuleType.nameStartsWith:
        return 'Name starts with "$pattern"';
      case RuleType.regex:
        return 'Regex: $pattern';
      case RuleType.company:
        return 'Company: ${_companyName(pattern)}';
    }
  }

  String get typeLabel {
    switch (type) {
      case RuleType.individual:
        return 'App';
      case RuleType.nameContains:
        return 'Contains';
      case RuleType.nameStartsWith:
        return 'Starts with';
      case RuleType.regex:
        return 'Regex';
      case RuleType.company:
        return 'Company';
    }
  }

  static String _companyName(String prefix) {
    final knownCompanies = {
      'com.facebook': 'Meta',
      'com.instagram': 'Meta',
      'com.whatsapp': 'Meta',
      'com.meta': 'Meta',
      'com.google': 'Google',
      'com.bytedance': 'ByteDance',
      'com.zhiliaoapp': 'ByteDance (TikTok)',
      'com.ss.android': 'ByteDance',
      'com.twitter': 'X (Twitter)',
      'com.x': 'X',
      'com.snap': 'Snap',
      'com.snapchat': 'Snap',
      'com.tencent': 'Tencent',
      'com.microsoft': 'Microsoft',
      'com.amazon': 'Amazon',
    };
    return knownCompanies[prefix] ?? prefix;
  }
}
